### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by adamstirtan** [KhaosT/homebridge-nest-cam#4]
Not really an issue but is there any way you can integrate in notifications when motion is detected?

**Comment by KhaosT** [comment]
For motion detection related notification, please use https://github.com/KraigM/homebridge-nest

**Comment by adamstirtan** [comment]
Ok thanks. Can I ask what the benefit or difference is between using this plugin and the other then?

**Comment by KhaosT** [comment]
This one only provides video stream for Nest Cam and that one only provides motion detection alert.

**Comment by adamstirtan** [comment]
Got it thanks. I’ll install the other one too. Thanks for your help!

**Comment by leoneleone** [comment]
@KhaosT @adamstirtan 

Relying on HomeKit to handle the snapshot of the motion event (homebridge-nest-cam + homebridge-nest) always comes back with a snapshot that is delayed and does not actually show a snapshot of the motion event itself, it gives a snapshot a few seconds after the Nest Motion Event.
This issue is a consistent one.

@KhaosT 
Is there any way we can link the Nest Camera's own img_url or animated_gif_url to supply HomeKit with the correct/accurate snapshot?
I hope we can give HomeKit access to the native Nest Cam snapshot, rather than having to rely on HomeKit's "delayed snapshot".
